import type { Coach } from '~/types/driving-school'
import { createGlobalState } from '@vueuse/core'
import { useCurd } from '~/hooks'

const initData: Coach[] = [
  {
    id: 1,
    username: 'coach001',
    password: '123456',
    name: '王大伟',
    phone: '13900001111',
    gender: '男',
    age: 40,
    teach_age: 12,
    intro: '科目二、科目三资深教练，耐心细致。',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coach001',
    click_num: 128,
    enabled: 1,
  },
  {
    id: 2,
    username: 'coach008',
    password: '123456',
    name: '张伟',
    phone: '13900008008',
    gender: '男',
    age: 38,
    teach_age: 10,
    intro: '科目二场地教学经验丰富。',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coach008',
    click_num: 96,
    enabled: 1,
  },
  {
    id: 3,
    username: 'coach003',
    password: '123456',
    name: '李壮壮',
    phone: '13900003003',
    gender: '男',
    age: 32,
    teach_age: 6,
    intro: '擅长 C2 自动挡教学。',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coach003',
    click_num: 72,
    enabled: 1,
  },
  {
    id: 4,
    username: 'coach004',
    password: '123456',
    name: '刘晓燕',
    phone: '13900004004',
    gender: '女',
    age: 34,
    teach_age: 7,
    intro: '细致耐心，学员好评率高。',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coach004',
    click_num: 88,
    enabled: 1,
  },
  {
    id: 5,
    username: 'coach005',
    password: '123456',
    name: '王娇娇',
    phone: '13900005005',
    gender: '女',
    age: 29,
    teach_age: 5,
    intro: '科目三路考专项教练。',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coach005',
    click_num: 65,
    enabled: 1,
  },
  {
    id: 6,
    username: 'coach002',
    password: '123456',
    name: '赵教练',
    phone: '13900002222',
    gender: '女',
    age: 35,
    teach_age: 8,
    intro: '擅长新手心理疏导与基础训练。',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=coach002',
    click_num: 86,
    enabled: 1,
  },
]

export const useCoachStore = createGlobalState(() => {
  return useCurd<Coach>({ key: 'driving-school-coaches-v3', initData })
})
