import type { Coach } from '~/types/driving-school'
import { createGlobalState } from '@vueuse/core'
import { useCurd } from '~/hooks'

const avatar = (seed: string) => `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}`

/** 与设计图 5.19 一致的教练假数据 */
const initData: Coach[] = [
  {
    id: 1,
    username: 'coach001',
    password: '123456',
    name: '王大伟',
    phone: '13823888888',
    gender: '男',
    age: 40,
    teach_age: 8,
    intro: '科目二、科目三资深教练，耐心细致。',
    avatar: avatar('coach001'),
    click_num: 19,
    comment_num: 1,
    favorite_num: 8,
    enabled: 1,
  },
  {
    id: 2,
    username: 'coach002',
    password: '123456',
    name: '胡相宇',
    phone: '13823888887',
    gender: '男',
    age: 36,
    teach_age: 6,
    intro: '科目二场地教学，通过率较高。',
    avatar: avatar('coach002'),
    click_num: 8,
    comment_num: 0,
    favorite_num: 7,
    enabled: 1,
  },
  {
    id: 3,
    username: 'coach005',
    password: '123456',
    name: '王卫国',
    phone: '13823888886',
    gender: '女',
    age: 29,
    teach_age: 4,
    intro: '科目三路考专项教练。',
    avatar: avatar('coach005'),
    click_num: 15,
    comment_num: 0,
    favorite_num: 6,
    enabled: 1,
  },
  {
    id: 4,
    username: 'coach008',
    password: '123456',
    name: '张伟',
    phone: '13900008008',
    gender: '男',
    age: 38,
    teach_age: 10,
    intro: 'C1 手动挡教学经验丰富。',
    avatar: avatar('coach008'),
    click_num: 96,
    comment_num: 3,
    favorite_num: 12,
    enabled: 1,
  },
  {
    id: 5,
    username: 'coach003',
    password: '123456',
    name: '李壮壮',
    phone: '13900003003',
    gender: '男',
    age: 32,
    teach_age: 6,
    intro: '擅长 C2 自动挡教学。',
    avatar: avatar('coach003'),
    click_num: 72,
    comment_num: 2,
    favorite_num: 9,
    enabled: 1,
  },
  {
    id: 6,
    username: 'coach004',
    password: '123456',
    name: '刘晓燕',
    phone: '13900004004',
    gender: '女',
    age: 34,
    teach_age: 7,
    intro: '细致耐心，学员好评率高。',
    avatar: avatar('coach004'),
    click_num: 88,
    comment_num: 4,
    favorite_num: 11,
    enabled: 1,
  },
  {
    id: 7,
    username: 'coach006',
    password: '123456',
    name: '孙立群',
    phone: '13823888885',
    gender: '男',
    age: 45,
    teach_age: 12,
    intro: '从业多年，擅长新手启蒙。',
    avatar: avatar('coach006'),
    click_num: 42,
    comment_num: 1,
    favorite_num: 5,
    enabled: 1,
  },
  {
    id: 8,
    username: 'coach007',
    password: '123456',
    name: '马丽娜',
    phone: '13823888884',
    gender: '女',
    age: 31,
    teach_age: 5,
    intro: '女性学员专属教练，沟通顺畅。',
    avatar: avatar('coach007'),
    click_num: 33,
    comment_num: 0,
    favorite_num: 4,
    enabled: 0,
  },
]

export const useCoachStore = createGlobalState(() => {
  return useCurd<Coach>({ key: 'driving-school-coaches-v4', initData })
})
